### PR TITLE
fix method chain with repository model.

### LINKED ISSUE #76: Failed enumerate with method chain.
Enumerate with method chain failed.

```
repos = bucket.repos('hirakiuc').select do |repo|
  repo.pull_requests.size > 1
end.map(&:full_name)
```

```
D, [2016-03-21T17:46:20.294568 #33311] DEBUG -- : [bitbucket.org] GET /api/2.0/repositories/hirakiuc (1.367 s)
/Users/hirakiuc/Desktop/github_repos/tinybucket/lib/tinybucket/api/helper/api_helper.rb:32:in `rescue in build_path': Failed to build request URL: Invalid repo_owner parameter. () (ArgumentError)
        from /Users/hirakiuc/Desktop/github_repos/tinybucket/lib/tinybucket/api/helper/api_helper.rb:23:in `build_path'
        from /Users/hirakiuc/Desktop/github_repos/tinybucket/lib/tinybucket/api/helper/pull_requests_helper.rb:48:in `base_path'
        from /Users/hirakiuc/Desktop/github_repos/tinybucket/lib/tinybucket/api/helper/pull_requests_helper.rb:10:in `path_to_list'
        from /Users/hirakiuc/Desktop/github_repos/tinybucket/lib/tinybucket/api/pull_requests_api.rb:24:in `list'
        from /Users/hirakiuc/Desktop/github_repos/tinybucket/lib/tinybucket/iterator.rb:39:in `load_next'
        from /Users/hirakiuc/Desktop/github_repos/tinybucket/lib/tinybucket/iterator.rb:18:in `size'
        from /Users/hirakiuc/Desktop/github_repos/tinybucket/lib/tinybucket/enumerator.rb:18:in `size'
        from app.rb:21:in `block in <main>'
        from /Users/hirakiuc/Desktop/github_repos/tinybucket/lib/tinybucket/enumerator.rb:8:in `yield'
        from /Users/hirakiuc/Desktop/github_repos/tinybucket/lib/tinybucket/enumerator.rb:8:in `block (2 levels) in initialize'
        from /Users/hirakiuc/Desktop/github_repos/tinybucket/lib/tinybucket/enumerator.rb:7:in `loop'
        from /Users/hirakiuc/Desktop/github_repos/tinybucket/lib/tinybucket/enumerator.rb:7:in `block in initialize'
        from app.rb:20:in `each'
        from app.rb:20:in `each'
        from app.rb:20:in `select'
        from app.rb:20:in `<main>'
```

### PR DESCRIPTION
**Pull request by hirakiuc**
Fix #76

### CODE REVIEW

File: lib/tinybucket/model/repository.rb [hunk 1]
```diff
@@ -50,6 +50,14 @@ class Repository < Base
         :has_issues, :is_private, :full_name, :name, :language,
         :website, :type
 
+      def initialize(json)
+        super(json)
+
+        if full_name && full_name.split('/').size == 2
```
Comment (hirakiuc) [inline lib/tinybucket/model/repository.rb]: `repo_owner` and `repo_slug` are not respond from Bitbucket API.

So these attributes should be set in tinybucket code.

**Comment by hirakiuc** [comment]
Tested by this code and this works fine.

```
repos = bucket.repos('hirakiuc').select do |repo|
  repo.pull_requests(state: 'MERGED').size > 1
end.map(&:full_name)
p repos
```

But this code does not work.

```
p bucket.repos('hirakiuc').select do |repo|
  repo.pull_requests(state: 'MERGED').size > 1
end.map(&:full_name)

=> 
#<Enumerator: #<Tinybucket::Enumerator: #<Enumerator::Generator:0x007fe8548bae18>:each>:select>
```

**Comment by hirakiuc** [comment]
> p bucket.repos('hirakiuc').select do |repo|
>  repo.pull_requests(state: 'MERGED').size > 1
> end.map(&:full_name)
> 
> => 
> #<Enumerator: #<Tinybucket::Enumerator: #<Enumerator::Generator:0x007fe8548bae18>:each>:select>

=> https://bugs.ruby-lang.org/issues/818

It is a enumerator behavior.
