### PR TITLE
fix undefined local variable error.

### LINKED ISSUE #109: undefined local variable or method `enum`
This error occurs when you call the undefined method to the subclass of `Tinybucket::Resource::Base.rb`.

=> [here](https://github.com/hirakiuc/tinybucket/blob/master/lib/tinybucket/resource/base.rb#L20).

### PR DESCRIPTION
**Pull request by hirakiuc**
Fix undefined local variable error.

This pull request fixes #109.

### CODE REVIEW

File: lib/tinybucket/resource/base.rb [hunk 1]
```diff
@@ -17,7 +17,7 @@ def method_missing(method, *args)
       end
 
       def respond_to_missing?(symbol, include_all)
-        enum.respond_to_missing?(symbol, include_all) || super
```
Comment (hirakiuc) [inline lib/tinybucket/resource/base.rb]: fixed two problems.

1. `enum`  is not defined in this scope. 😢 
2. I think, this `respond_to_missing?` should not depend on `super` because I want to forward the methods to the enumerator, not super.

**Comment by hirakiuc** [comment]
Looks good to me 👍
